[package]
name = "rust_c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
reqwest = { version = "0.12.9", features =["json","rustls-tls"], default-features = false }
serde_json = "1.0.132"
serde = { version = "1.0", features = ["derive"] }